# Copyright 2023 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'build-Corne-ish-Eyelash-nice_nano_v2-nice_view'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["corne_left nice_view_adapter nice_view","corne_right nice_view_adapter nice_view"]'
#      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=y"]'


#     custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
#      kconfig: '["CONFIG_ZMK_MOUSE=y"]'
#      branches: '["petejohanson/zmk/feat/pointers-move-scroll","zmkfirmware/zmk/main petejohanson/zmk/feat/pointers-move-scroll"]'
#
#      custom_config: '["#define MIRYOKU_KLUDGE_SOFT_OFF"]'
#      kconfig: '["CONFIG_ZMK_PM_SOFT_OFF=y"]'



#      board: '[
#        "corneish_zen_v1_left","corneish_zen_v1_right",
#        "corneish_zen_v2_left","corneish_zen_v2_right"
#      ]'
#      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
#      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY=y\nCONFIG_CUSTOM_WIDGET_LAYER_STATUS_HIDE_HEADING=y\nCONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y\nCONFIG_IL0323_INVERT=y"]'
#      branches: '["zmkfirmware/zmk/main caksoylar/zmk/caksoylar/zen-v1+v2 petejohanson/zmk/feat/pointers-move-scroll"]'
